### ISSUE TITLE
Figure out appropriate way to make predictions at event boundaries

### ISSUE THREAD

**Issue by tomov** [nicktfranklin/SEM#5]
Requires some investigation.

Say we have the following "true" event sequence: AAAAABBBBBCCCCC, so e1..e5 = A, e6..e10 = B, and e11..e15 = C.
Say we've segmented s1..s10 correctly and now we're at s11.

We have three options for the event type of s11:
1) the current event type (B)
2) a previously seen event type (A)
3) a previously unseen event type (C)

How do we compute the likelihood of s11 in each of these?

Case 1 is straightforward -- we feed the previous scene s10 to the current event model B to get the predicted next scene s11.

Case 2 is not so straightforward, because of the implied event boundary. Several options:
- Same as case 1, except using the event type under consideration (A). This is what we currently do. That doesn't make a lot of sense though -- if we believe there is an event boundary between s10 and s11, why would we want to use s10 to predict s11 (unless we're predicting across events, which is not in the framework but is definitely an interesting question)? Notice that this is not much of an issue once we're at s12. The implication is that we would consistently make incorrect predictions for the first scene after an event boundary, but would quickly correct ourselves.
- Predict the average scene for the event type under consideration. Assumes that scenes from each event type tend to cluster around the same area of scene space.
- Predict the average initial scene for the event type under consideration. Assumes that each sequence of scenes from an event type tends to start from the same area of scene space.
- Feed some "null" scene (instead of s10) to the event model under consideration. If the event model is general enough (e.g. a fancy RNN), it should eventually learn that "null" scene means start of a new sequence and figure out what the best predictions is there.
- Predict some "null" scene

Case 3 is even less straightforward, because we don't have an initialized event model. Options:
- Same as case 1, except using a newly initialized event model with random parameters. Currently we do something of this sort, except we should look more carefully at how we do it for the different event models.
- Feed "null" scene (instead of s10) to newly initialized event model. Risks significantly lowering the probability of picking a new event type (if the initial weights are too constrained).
- Predict the "null" scene.
- Predict the last scene s10. Risks always selecting new event types if you have a sequence of identical scenes (which seems like it should suggest the same event type).

**Comment by tomov** [comment]
Sam's suggestion: a principled thing to do is to treat the prediction f(0) as a learnable, free parameter for the model.

Momchil: So we could have one free parameter for each event model's f(0), as well as a global free parameter for the f(0) of any new event model.

**Comment by tomov** [comment]
Another thing that might be worth speculating about is continuous events that can get interrupted but then resume from where they left off (i.e. predicting f(0) based on the last scene last time we saw that event).

**Comment by nicktfranklin** [comment]
added methods "predict_f0" and "update_f0" to event model class, and updated SEM to use these. in the neural network versions of the event models, this is done by feeding in a zero vector to the event model such that f0 = f(0)

See pull request #8
