### ISSUE TITLE
Play around with resegmentation

### ISSUE THREAD

**Issue by tomov** [nicktfranklin/SEM#6]
Could do something like particle filtering, where each particle = hypothesis about the event sequence (rather than considering the MAP only).

Could include pruning of unlikely hypothesis (e..g as you accumulate more scenes of the same event type) and resampling at moment of high uncertainty (e.g. at event boundaries when there's lots of potential candidate events). Would address the problem of how do you determine the event type given a single scene after an event boundary. Would also make distinct predictions about order effects (e.g. events that start off similarly but evolve differently -> do people re-assign the initial scenes to the eventually inferred event?).

Alternatively, could do something more naive like only considering the last K scenes (e.g. last 3 scenes) for resegmentation, and only testing the hypothesis that they all belong to the currently active event type vs. that they were segmented correctly the first time. Would again address the issue of segmenting at event boundaries.

Notice this makes a difference both for prediction (it could turn out that we're more likely to be in a bar fight but only if we consider the full history of scenes from the beginning, which we may have assigned to a different event type already, e.g. an academic debate) as well as for training (we should train the bar fight model on those scenes too; conversely, even though we may not be able to "untrain" the academic debate model, we could remove them from its "episodic memory" if we're doing batch gradient descent later on).

**Comment by nicktfranklin** [comment]
One idea is Discrete Particle Variational inference: [Paper Here](https://arxiv.org/pdf/1402.5715.pdf).  The intuition is a particle filter with the K highest posterior probability particles.  

It's probably memory intensive but it would allow for a distribution over segmentation and retrospective revaluation. One key drawback is that it requires "mutation" of the particles -- i.e. changing the latent variables (the event label). This would require reestimating the statistics of the event models.
